server:
  hostname: irc.awesome.cool
  port: 443
  use_tls: true
  check_certificates: true
  channels:
    - "#general"
    - "#off-topic"
user:
  username: Isidore
  mode: 0
  realname: Isidore Beautrelet
client:
  sent_history_length: 65536
  channel_history_length: 65536
